FROM python:3.13-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ui.py .
COPY samples ./samples

EXPOSE 8501
CMD ["python", "-m", "streamlit", "run", "ui.py", "--server.address", "0.0.0.0"]

